name: corona-ai
channels:
  - conda-forge

dependencies:
  - python==3.8.3
  - pip
  - matplotlib
  - pandas
  - pip:
      - deepspeech==0.6.1
      - fastapi==0.59.0
      - numpy==1.18.2
      - phue==1.1
      - Pillow==7.1.1
      - PyAudio==0.2.11
      - scipy==1.5.1
      - uvicorn==0.11.6
      - webrtcvad==2.0.10
      - websockets==8.1
